
import { jsPDF } from 'jspdf';
import { OrderData, ProcessedFile } from '@/types';

export const generatePDF = (
  fileData: ProcessedFile,
  selectedDay?: string,
  selectedOrderId?: string
): { pdf: jsPDF; pageCount: number } => {
  // Create a new PDF document
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  // Filter orders based on selected day or order ID
  let ordersToInclude = fileData.orders;
  if (selectedDay) {
    ordersToInclude = ordersToInclude.filter(order => order.day === selectedDay);
  }
  if (selectedOrderId) {
    ordersToInclude = ordersToInclude.filter(order => order.id === selectedOrderId);
  }
  
  // Set initial page and position
  let currentPage = 1;
  let yPosition = 30;
  const maxY = 280; // Maximum y-position before creating a new page
  
  // Add header to first page
  addHeader(pdf, fileData);
  
  // Process each order
  ordersToInclude.forEach((order, index) => {
    // Check if we need a new page
    if (yPosition > maxY) {
      pdf.addPage();
      currentPage++;
      yPosition = 30;
      addHeader(pdf, fileData);
    }
    
    // Add order details
    addOrderDetails(pdf, order, yPosition);
    yPosition += 40; // Move y-position for next order
  });
  
  // Add footer with page numbers to each page
  for (let i = 1; i <= currentPage; i++) {
    pdf.setPage(i);
    addFooter(pdf, i, currentPage, fileData);
  }
  
  return { pdf, pageCount: currentPage };
};

const addHeader = (pdf: jsPDF, fileData: ProcessedFile) => {
  // Add DHL-inspired header
  pdf.setFillColor(255, 204, 0); // DHL Yellow
  pdf.rect(0, 0, 210, 20, 'F');
  
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(212, 5, 17); // DHL Red
  pdf.setFontSize(16);
  pdf.text('Order Summary Report', 105, 12, { align: 'center' });
  
  // Add file metadata
  pdf.setFontSize(10);
  pdf.setTextColor(85, 85, 85); // Dark gray
  pdf.setFont('helvetica', 'normal');
  pdf.text(`File: ${fileData.fileName}`, 10, 25);
  pdf.text(`Date: ${fileData.uploadDate}`, 10, 30);
  pdf.text(`Uploaded by: ${fileData.uploadedBy}`, 10, 35);
};

const addOrderDetails = (pdf: jsPDF, order: OrderData, y: number) => {
  // Add box for each order
  pdf.setFillColor(245, 245, 245);
  pdf.roundedRect(20, y - 5, 170, 35, 3, 3, 'F');
  
  // Add border with DHL yellow
  pdf.setDrawColor(255, 204, 0);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(20, y - 5, 170, 35, 3, 3, 'S');
  
  // Add order details
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0);
  pdf.setFontSize(12);
  pdf.text(`Day: ${order.day}`, 25, y + 5);
  pdf.text(`Order: ${order.order}`, 25, y + 15);
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.text(`Supplier: ${order.supplier}`, 25, y + 25);
  
  if (order.details) {
    pdf.setFontSize(10);
    pdf.setTextColor(85, 85, 85);
    pdf.text(`Details: ${order.details}`, 120, y + 15);
  }
};

const addFooter = (pdf: jsPDF, currentPage: number, totalPages: number, fileData: ProcessedFile) => {
  pdf.setFillColor(212, 5, 17); // DHL Red
  pdf.rect(0, 287, 210, 10, 'F');
  
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(255);
  pdf.text(`Page ${currentPage} of ${totalPages}`, 105, 293, { align: 'center' });
  
  // Add copyright or company info
  pdf.text('Generated by Express Excel Ship', 20, 293);
  pdf.text(new Date().toLocaleDateString(), 180, 293);
};
