import { Printer, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Order } from "@/lib/orders";

export const OrdersTable = ({ orders, count, search, onSearch, onPrint }: { orders: Order[]; count: number; search: string; onSearch: (value: string) => void; onPrint: (order: Order) => void }) => (
  <section aria-labelledby="orders-heading" className="min-w-0 border-t border-border pt-7">
    <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="step-label">03 / REVISAR PEDIDOS</p><h2 id="orders-heading" className="text-2xl font-bold">Pedidos de la jornada</h2><p className="text-sm text-muted-foreground">{orders.length} de {count} pedidos visibles. La búsqueda no cambia el PDF de jornada.</p></div><label className="relative w-full sm:w-72"><span className="sr-only">Buscar pedido o proveedor</span><Search aria-hidden="true" className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Buscar pedido o proveedor" className="pl-9" /></label></div>
    {orders.length ? <div className="divide-y border-y border-black/30 lg:hidden">{orders.map((order) => <div key={order.id} className="grid grid-cols-[1fr_auto] gap-2 py-4"><div className="min-w-0"><strong className="block text-lg">{order.orderNumber}</strong><p className="break-words text-sm">{order.supplier}</p><p className="mt-1 text-xs text-muted-foreground">{order.day} · {order.boxes} cajas</p></div><Button variant="outline" size="sm" onClick={() => onPrint(order)} aria-label={`Preparar PDF del pedido ${order.orderNumber}`}><Printer className="size-4" /> PDF</Button></div>)}</div> : <p className="border-y py-8 text-sm">No hay pedidos que coincidan con la búsqueda.</p>}
    {!!orders.length && <table className="hidden w-full table-fixed text-left text-sm lg:table"><thead className="border-y border-black/40 bg-[#F5F5F3] text-xs uppercase"><tr><th className="w-[22%] px-3 py-3">Pedido</th><th className="w-[42%] px-3 py-3">Proveedor</th><th className="w-[13%] px-3 py-3">Cajas</th><th className="w-[12%] px-3 py-3">Día</th><th className="w-[11%] px-3 py-3">Acción</th></tr></thead><tbody className="divide-y divide-border">{orders.map((order) => <tr key={order.id} className="hover:bg-[#FFF8DC]"><td className="break-all px-3 py-3 text-base font-bold">{order.orderNumber}</td><td className="break-words px-3 py-3">{order.supplier}</td><td className="px-3 py-3 font-semibold">{order.boxes}</td><td className="px-3 py-3">{order.day}</td><td className="px-3 py-3"><Button variant="outline" size="sm" title={`Preparar PDF del pedido ${order.orderNumber}`} aria-label={`Preparar PDF del pedido ${order.orderNumber}`} onClick={() => onPrint(order)}><Printer className="size-4" /> PDF</Button></td></tr>)}</tbody></table>}
  </section>
);
