// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfhwvkrwifyrjdiiarjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaHd2a3J3aWZ5cmpkaWlhcmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MjYwOTEsImV4cCI6MjA1OTMwMjA5MX0.JA2Tw2kA4xdhlXY8ZQLU0E30q1JsQO7a1vRsC3wfL9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);